### ISSUE TITLE
arduino live

### ISSUE THREAD

**Issue by Vayel** [Poztit/pyDuino#2]
A quoi sert ce dossier ?

**Comment by fillien** [comment]
Arduino live est un programme à implanter dans une Arduino pour pourvoir la commander sur un PC via l'interface serie.

**Comment by Vayel** [comment]
Quel rapport avec pcduino ?

**Comment by fillien** [comment]
Aucun, mais ça permet de contrôler une Arduino en python. Donc par exemple t'a un pcduino et une Arduino: tu contrôle les deux en même temps et en python.

**Comment by Vayel** [comment]
Désolé, je voulais dire pyduino.

**Comment by Vayel** [comment]
Mais du coup, quel rapport avec pyduino ?

**Comment by fillien** [comment]
Tu veus l'enlever ?

**Comment by Vayel** [comment]
Si ça n'a pas de rapport avec pyduino, oui.

**Comment by fillien** [comment]
Yep mais c'est un super outil.

**Comment by Vayel** [comment]
Il suffit de lui dédier un dépôt.
