### ISSUE TITLE
PEP-08

### ISSUE THREAD

**Issue by Vayel** [Poztit/pyDuino#9]
Il nous faut respecter la PEP-08. Pour cela, je propose d'utiliser [PyLint](http://www.pylint.org/). Se pose la question des formats des noms : conserve-t-on la norme Arduino (camelCase) ou transforme-t-on tout cela en Python (snake_case) ?

**Comment by fillien** [comment]
Il faut garder la norme Arduino.

**Comment by Vayel** [comment]
Ok. Je m'occupe du fichier de configuration de PyLint. Je ne l'intègre pas tout de suite à Travis, sinon aucune de nos PR ne passera.

**Comment by fillien** [comment]
Ok pas de problème, je le fais tourner en local.

**Comment by fillien** [comment]
Je commence avec le module core.base

**Comment by Vayel** [comment]
Justement, je l'avais commencé. x)

**Comment by fillien** [comment]
bon bah je fais common

**Comment by Vayel** [comment]
Il y a quoi comment exception à la PEP-08 à part les noms ?

**Comment by fillien** [comment]
Serial, Ethernet autrement rien, pour être sur il faudrais demandé a Sensor56

**Comment by Vayel** [comment]
> Serial, Ethernet

?

**Comment by fillien** [comment]
Regarde les mots réservés en language Arduino (C++ modifié)

**Comment by fillien** [comment]
PyLint dit que des variables sont des CONSTANTE.

**Comment by fillien** [comment]
Je fais libs du coup

**Comment by fillien** [comment]
Tu aurait une configuration pour Pylint ?

**Comment by Vayel** [comment]
J'en ai pushé une sur dev.

**Comment by Vayel** [comment]
J'ai renommé le fichier : il est maintenant pris automatiquement en compte quand tu fais `pylint file.py`.

**Comment by fillien** [comment]
Ok.

**Comment by fillien** [comment]
Comment faire pour les `unused import`, car certaines fonctions (exe: sin) doivent être presentes.

**Comment by Vayel** [comment]
Justement, je voulais t'en parler. Pourquoi _doivent_-elles être présentes ? Il me semble plus judicieux d'utiliser la bibliothèque standard de manière... standard.

**Comment by fillien** [comment]
Elle doivent être présentent dans le language Arduino.

**Comment by Vayel** [comment]
Pourquoi ne pas tirer parti du fait qu'elles sont présentes dans Python de base ? Il suffit juste de l'indiquer dans la doc.

**Comment by fillien** [comment]
Pour l'utilisateur cela dois déjà être fait.

**Comment by fillien** [comment]
Les lignes de 79 caractères nuissent à la lecture du code.

**Comment by Vayel** [comment]
Comment ça ?

**Comment by fillien** [comment]
Être limité à 79 carac (comme avant) est très embêtant dans certains cas.

**Comment by Vayel** [comment]
Exemple ?

**Comment by fillien** [comment]
base.py 167

``` Python
return (valeur - in_min) * (out_max - out_min) / (in_max - in_min) + out_min
```

to

``` Python
return ((valeur - in_min) *
    (out_max - out_min) /
    (in_max - in_min) +
    out_min)
```

**Comment by Vayel** [comment]
Il suffit de créer des variables intermédiaires, ce qui rend au passage le code plus clair (là, on a une grosse formule pas très explicite).

**Comment by fillien** [comment]
Ça coûte plus en mémoire sur le moment.

**Comment by fillien** [comment]
system.py 228

``` Python
onlydirs = [f for f in os.listdir(pathIn) if os.path.isdir(os.path.join(pathIn, f))]
```

**Comment by Vayel** [comment]
```
onlydirs = [f for f in os.listdir(pathIn)
            if os.path.isdir(os.path.join(pathIn, f))]
```

J'y peux pas grand chose si c'est la convention.

**Comment by fillien** [comment]
Oui.

**Comment by fillien** [comment]
T'es sur quoi là ?

**Comment by Vayel** [comment]
core.base

**Comment by fillien** [comment]
Ok

**Comment by fillien** [comment]
J'ai testé flake8, je le trouve beaucoup moins embêtant que Pylint. Tu en pense quoi ?

**Comment by Vayel** [comment]
Si tu préfères, vas-y. ^^

Mais peut-on le configurer pour permettre le camelCase en nom de fonctions ?

Quels points te gênent avec PyLint ?

**Comment by fillien** [comment]
Ok je vais commit un fichier de configuration, je garde celui de PyLint au cas où. Il accepte par défaut le camelCase pour les fonctions. PyLint me gêne parce que par exemple, il fais un mauvais distinguo entre les variables et les constantes.

**Comment by Vayel** [comment]
> PyLint me gêne parce que par exemple, il fais un mauvais distinguo entre les variables et les constantes.

Genre où ? :)

**Comment by fillien** [comment]
common.py

**Comment by Vayel** [comment]
Ben ce sont des constantes dans common.py, non ? Je ne vois pas l'intérêt d'y mettre des variables.

**Comment by fillien** [comment]
common.py contient des variables globales et des constantes globales. PyLint ne fais pas la différence, donc il te sort pleins d'erreurs qui non pas lieu d'être.

**Comment by fillien** [comment]
Tu as fini `base.py` ?

**Comment by Vayel** [comment]
Quel est l'intérêt de définir des _variables_ globales ? Quand tu importes `common.py`, son devient s'intègre dans le contexte du module l'important : tout ce que tu modifies (les variables) n'est pas répercuté sur le reste. Du coup, je ne vois pas l'intérêt de définir des variables dans `common.py`.

Non. Je n'ai pas trop de temps en ce moment.

**Comment by fillien** [comment]
Excuse moi, je voulais dire communes, elles sont tous initialisé dans `common.py`

**Comment by Vayel** [comment]
Faisons la liste des variables ^^ :
- [noLoop](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L20) : c'est une constante.
- [debug](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L21) : constante.
- [Uart](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L31) : à quoi cela sert-il de l'initialiser ici ?
- [uartPort](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L32) : même question.
- [Serial](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L35) : même question.
- [Ethernet](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L36) : même question.
- [home_dir](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L40) : constante.
- [main_dir](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L41) : constante.
- [data_dir_*](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L51) : constante.
- [pathMode](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L69) : à quoi cela sert-il de l'initialiser ici ?
- [pathState](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L70) : même question.
- [micros0Syst](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L83) : même question.
- [millis0Syst](https://github.com/Poztit/pyDuino/blob/master/pyduino/core/common.py#L84) : même question.

**Comment by fillien** [comment]
micro0Syst et millis0Syst c'est des constantes. Uart, uartPort, Serial, Ethernet, pathMode et pathState : je suis d'accord avec toi ça na rien à faire ici.

**Comment by fillien** [comment]
Si tu veus, je fais `base.py` et je fini les modules plateformes. Après il faudra entamer la traduction.

**Comment by Vayel** [comment]
Je veux bien. Je peux m'occuper de la traduction si tu veux.

**Comment by fillien** [comment]
Ça marche.

**Comment by Vayel** [comment]
Quels modules puis-je commencer à traduire ?

**Comment by fillien** [comment]
N'importe, choisit :-D.
